techmatters/soil-id-algorithm

- NRCS_SDA_Demos/Leaflet_SSURGO_Poly_WMS.Rmd
- python_code/local_functions_SoilID_v3.py
- python_code/soilIDModel_v3.py
> Code changes

- NRCS_SDA_Demos/Leaflet_SSURGO_Poly_WMS.Rmd
- python_code/local_functions_SoilID_v3.py
- python_code/multi_sim_triangular.py
- python_code/soilIDModel_v3.py
> Functional similarity algorithm

- python_code/README_API.md
- python_code/local_functions_SoilID_v3.py
- python_code/soilIDModel_v3.py
> Code update from Jonathan

- .editorconfig
- Makefile
- python_code/README_API.md
- python_code/local_functions_SoilID_v3.py
- python_code/multi_sim_triangular.py
- python_code/soilIDModel_v3.py
* format python code with black and isort
* add `Makefile` and `.editorconfig`
> fix: format python code with black and isort

- pyproject.toml
- python_code/local_functions_SoilID_v3.py
- python_code/multi_sim_triangular.py
- python_code/soilIDModel_v3.py
- setup.cfg
* Add `setup.cfg` and `pyproject.toml`
* Wrap long lines
* remove unused and duplicate imports
> fix: add code formatting config + fix additional formatting errors

- .github/workflows/build.yml
- requirements-dev.txt
> chore: add linting workflow

- python_code/local_functions_SoilID_v3.py
- python_code/soilIDModel_v3.py
* Import functions by name instead of with *
* fix spelling of `get_datastore_connection()`
* note unused functions in comment
> fix: clean up imports

- python_code/local_functions_SoilID_v3.py
- python_code/multi_sim_triangular.py
- python_code/soilIDModel_v3.py
> fix: merge code updates to main

- python_code/local_functions_SoilID_v3.py
- python_code/multi_sim_triangular.py
- python_code/soilIDModel_v3.py
Restore code formatting lost in merge.
> style: format code after merge

- python_code/local_functions_SoilID_v3.py
- python_code/soilIDModel_v3.py
* remove unused imports
* update function names to match what is used in local_functions
> fix: update imports

- python_code/local_functions_SoilID_v3.py
- python_code/soilIDModel_US_v3.py
> fix: API bug fixes

- python_code/local_functions_SoilID_v3.py
- python_code/soilIDModel_Global_v3.py
- python_code/soilIDModel_US_v3.py
Fixed Flake8 errors for soilIDModel_Global_v3.py, soilIDModel_US_v3.py, and local_functions_SoilID_v3.py
> fix: flake8 errors

- soil_id/config.py
- soil_id/db.py
- soil_id/global_soil.py
- soil_id/us_soil.py
- soil_id/utils.py
Move database code into is own file.
> refactor: move database code into is own file

- soil_id/global_soil.py
- soil_id/services.py
- soil_id/us_soil.py
- soil_id/utils.py
Move API calls to services.py. Consistently pass parameters to requests.get() — no more urllib calls.
> refactor: move API calls to services.py

- soil_id/color.py
- soil_id/us_soil.py
- soil_id/utils.py
Move color helpers to separate file.
> refactor: move color helpers to separate file

- soil_id/tests/us/test_us.py
- soil_id/us_soil.py
- soil_id/utils.py
Remove dead code
- remove unreachable blocks
- remove unused variables/parameters
(found via vulture)
@jjmaynard  do we want to use `getColor_deltaE2000_OSD_pedon`? There is a comment:
>TODO: Future testing to see if deltaE2000 values should be incorporated
into site data use 'getColor_deltaE2000_OSD_pedon' and helper functions
located in utils.py
Fixes #36.
> fix: remove dead code

- soil_id/utils.py
For logger, warning() instead of warn().
> fix: use warning() instead of warn

- .github/workflows/build.yml
- soil_id/tests/us/test_us.py
Check out data for testing. Currently includes 
* gsmsoilmu_a_us shapefile
* LandPKS_munsell_rgb_lab.csv
> chore: check out data for testing

- soil_id/color.py
use f-string for munsell colors.
> fix: use f-string for munsell colors

- soil_id/services.py
- soil_id/soil_sim.py
- soil_id/tests/us/test_us.py
- soil_id/us_soil.py
- soil_id/utils.py
-separated site-based calculations.
- created new library for functional similarity simulation (site_sim.py)
- separated continuous depth calculations and other calculations needed for soilidrank
> fix: separate site-based calculations from main getSoilLocationBasedUS

- soil_id/services.py
Standardize API error logging and returning.
> fix: standardize API error logging and returning

- Makefile
- requirements-dev.txt
- requirements.txt
- requirements/base.in
- requirements/dev.in
- soil_id/color.py
- soil_id/config.py
- soil_id/tests/us/test_us.py
- soil_id/us_soil.py
- soil_id/utils.py
- add performance graphs
- use scikit for rgb2lab call
- add requests caching support
> fix: add performance graphs, use scikit for rgb2lab call, add requests caching support

- Makefile
- requirements.txt
- requirements/base.in
Move rosetta-soil to standard dependency list.
> fix: move rosetta-soil to standard dependency list

- .github/workflows/build.yml
> chore: bump python to 3.12.3

- soil_id/us_soil.py
Missing indent for code chunk resulting in error when running with site_calc=True
> fix: bug fix for site-calc

- soil_id/tests/us/test_us.py
- soil_id/us_soil.py
Refactors the us_soil code to separate the concerns of running the algorithm from figuring out how to store the resulting data so downstream consumers can choose how to do this. Also makes the code more testable.  In draft until I finish the backend PR integrating this change.
Needed for https://github.com/techmatters/terraso-backend/issues/1270
Everything should work the same.
> refactor: return data from soil id algorithm instead of writing to disk

- soil_id/us_soil.py
Handles the case where the vertical cracking input hasn't been completed. Confirmed with jon we just assume there is no cracking in this case.
> fix: handle cracks = None case

- soil_id/config.py
- soil_id/utils.py
-fixed awc calculation bug. Modified infilling to prevent populating data frame with negative values
-added random seed for simulations
Fixes #102.
> fix: add random seed and fixed data infilling to prevent negative values

- soil_id/tests/us/test_us.py
- soil_id/us_soil.py
Fixes #113, adds a test which triggers the (former) bug.
> fix: don't crash on empty data

- soil_id/us_soil.py
fix crashes (No objects to concatenate, Could not broadcast input array)
Fixes #111.
Fixes #112.
> fix: fix crashes (No objects to concatenate, Could not broadcast input array)

- .github/workflows/build.yml
- requirements.txt
- requirements/base.in
> build: bump gdal to 3.9.1

- requirements.txt
- requirements/base.in
- soil_id/utils.py
bump geopandas from 0.14.4. to  1.0.1.
> build: bump geopandas from 0.14.4. to  1.0.1

- Makefile
- README.md
- soil_id/tests/us/generate_bulk_test_results.py
- soil_id/tests/us/process_bulk_test_results.py
- soil_id/tests/us/test_us.py
Adds some more coordinates to the CI testing infrastructure, and adds scripts to run a large manual test. See updated README for usage instructions.
Fixes #8 
Should be able to run the tests, and they should pass (or yield expected statistical outcomes).
> tests: add more coordinates to testing, including 3k coordinate bulk testing script

- .github/workflows/build.yml
- requirements-dev.txt
- requirements.txt
> build: update platformdirs and GDAL

- scripts/rebuild.sh
- setup.py
- soil_id/__init__.py
- soil_id/color.py
- soil_id/config.py
- soil_id/db.py
- soil_id/global_soil.py
- soil_id/services.py
- soil_id/soil_sim.py
- soil_id/tests/global/test_global.py
- soil_id/tests/us/generate_bulk_test_results.py
- soil_id/tests/us/process_bulk_test_results.py
- soil_id/tests/us/test_us.py
- soil_id/us_soil.py
- soil_id/utils.py
Add copyright notice to source files.
> docs: add copyright notice

- requirements.txt
- requirements/base.in
> build: update GDAL to 3.9.3

- soil_id/services.py
Update SoilWeb API endpoint to new production endpoint.
> fix: update SoilWeb API endpoint

- .github/workflows/build.yml
> build: update python to 3.13.1

- soil_id/us_soil.py
- Bug fix - code update to fix scaling issue with the Data + Location score. No longer scales to 100%.
> fix: scaling bug for Data_location score

- .github/workflows/build.yml
> build: update python to 3.13.2

- Makefile
remove pip tools makefile. restore --upgrade.
> fix: remove pip tools makefile. restore --upgrade

- .github/workflows/build.yml
- requirements.txt
- requirements/base.in
update GDAL to 3.10.3 and Python to 3.13.3
> build: update GDAL to 3.10.3 and Python to 3.13.3

- .github/workflows/auto-approve.yml
auto-approve dependabot PRs, like in other repos
> build: auto-approve dependabot PRs

- .pre-commit-config.yaml
update ruff version in pre-commit-config
> build: update ruff version in pre-commit-config

- .github/workflows/build.yml
> fix: update python to 3.13.7

- .pre-commit-config.yaml
update pre-commit config
- use ruff-check instead of ruff
- update conventional-pre-commit version
> fix: update pre-commit config
